package component:example;

interface greeter {
    greet: func(who: string);
}

/// An example world for the component to target.
world example {
    export hello-world: func() -> string;

    import greeter;
}
